### ISSUE TITLE
Locale issue on Arch

### ISSUE THREAD

**Issue by milasudril** [milasudril/anja#113]
It appears that there is a problem with using the C.UTF-8 locale on Arch:

```
doc/index.sh: line 29: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
Traceback (most recent call last):
  File "doc/makepage.py", line 603, in <module>
    main(sys.argv[1:])
  File "doc/makepage.py", line 538, in main
    tree=ET.parse(sys.stdin)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 6, column 14
Error: I/O errordoc/index.xml: Compilation failed with status 1.
make: *** [Makefile:4: release] Error 255
make  114.35s user 10.03s system 72% cpu 2:51.76 total```

This breaks compilation of the HTML version of the manual.

**Comment by milkmiruku** [comment]
```
$ locale -a
C
en_GB.utf8
POSIX
```

[locale](https://wiki.archlinux.org/index.php/locale) on the Arch Wiki

The non-zero exit code is a problem for creating an Arch PKGBUILD. [Here's](https://gist.github.com/milkmiruku/71b1cb204353d7467e47dfaf8018ec14) my incomplete PKGBUILD for Anja.

**Comment by milkmiruku** [comment]
commercialhaskell/stack#856 appears to have the answer

**Comment by milasudril** [comment]
Try to change the script so it changes the locale to C or POSIX instead. I need to verify that it works on Ubuntu though.

**Comment by milkmiruku** [comment]
I tried just "C" but it failed, then "POSIX", but that failed also, so I tried "en_GB.utf8" and it was juuust right! :)

With a hacky sed change, the PKGBUILD works. [Anja is now in the AUR](https://aur.archlinux.org/packages/anja-git/).

**Comment by milkmiruku** [comment]
That appears to work, thanks! I've updated the PKGBUILD in the AUR.
