### ISSUE TITLE
Sample can be sustained without the option enabled by change of window area focus

### ISSUE THREAD

**Issue by milkmiruku** [milasudril/anja#118]
If one has the keyboard active, presses a key to play a sample (that doesn't have sustain enabled), clicks to any tab below, then releases the key, the note is sustained due to no detected unpress and thus no note off (until another [note on press then] note off unpress) or the end of the sample (if not looped - if looped, one can actually achieve a sustain and loop at the same time).

It's a small problem that is arguably caused by the device between the keyboard and chair, but an unexpected and confusing one. If sustain is to appear, sustain should be selected.

Maybe firing automatic note offs when the keyboard area becomes unfocused (when sustain isn't on)?

(Further, possibly an option for a first press play second press stop type toggled playback could be a utilisation of aspects of the current behaviour.)

**Comment by milasudril** [comment]
Good point. Moving focus should trigger a regular NOTE_OFF (so that any decay part will still be played).

**Comment by milasudril** [comment]
I will make this feature optional, as there are usecases when this is not desired. For example, when anja running as a synthesizer triggered by external inut.
