### ISSUE TITLE
Feature request: 'Kill all' audio method/button without engine restart

### ISSUE THREAD

**Issue by milkmiruku** [milasudril/anja#120]
The manual references in 1.2 "an exposed kill all feature (see Section 3.3)", but the closest 3.3 talks about a 'single point' of killing audio is the the engine [state], and this method requires two clicks (on different buttons) and loses Jack connections. Could the sidebar get an extra 'Kill all' button just below the engine buttons to just squash all playing audio out?

**Comment by milasudril** [comment]
Did you try the Del key https://milasudril.github.io/anja/#keybindings. But yes, there could be a button in the sidebar as well.

**Comment by milasudril** [comment]
Ctrl + key  is waveform capture.
